Object: Matrix Addition, Substraction and Multiplication 

In [2]:
#Matrix Declaration/Creation
def getm(r,c):
    m = [[0]*c for _ in range(r)]
    for i in range(r):
        for j in range(c):
            m[i][j] = int(input())
    return m

In [3]:
#Print Matrix
def printm(m:list):
    for i in range(len(m)):
        for j in range(len(m[0])):
            print(m[i][j],end=' ')
        print()


In [4]:
A = [[1,2],[3,4]]
B = [[5,6],[7,8]]
C = [[0]*2 for i in range(2)]

print('Matrix A:')
printm(A)
print('Matrix B:')
printm(B)

# Matrix Addition
for i in range(2):
    for j in range(2):
        C[i][j] = A[i][j] + B[i][j]
print('Matrix C:')
printm(C)

Matrix A:
1 2 
3 4 
Matrix B:
5 6 
7 8 
Matrix C:
6 8 
10 12 


In [5]:
# Function to initialize a matrix
def initM(r,c):
    m = [[0]*c for _ in range(r)]
    return m

In [6]:
# Matrix Multiplication
print("Enter Rows and Columns for First Matrix:")
m = int(input("Rows:"))
n = int(input("Columns:"))
M1 = getm(m,n)
print("First Matrix:")
printm(M1)
print("Enter Rows and Columns for Second Matrix:")
p = int(input("Rows:"))
q = int(input("Columns:"))
M2 = getm(p,q)
print("Second Matrix:")
printm(M2)
if n!=p:
    print("Multiplication not possible!")
    exit()
M3 = initM(m,q)

for i in range(m):
    for j in range(q):
        for k in range(n):
            M3[i][j] += (M1[i][k] * M2[k][j])
print("Result of Matrix Multiplication:")
printm(M3)


Enter Rows and Columns for First Matrix:
First Matrix:
1 1 
1 1 
Enter Rows and Columns for Second Matrix:
Second Matrix:
1 2 
3 4 
Result of Matrix Multiplication:
4 6 
4 6 


In [7]:
# using list comprehension
l1 = [[1 for i in range(2)] for j in range(2)]
l2 = [[i+1 for i in range(2)] for j in range(2)]

print("l1:\n",l1)
print("l2:\n",l2)


l1:
 [[1, 1], [1, 1]]
l2:
 [[1, 2], [1, 2]]


In [8]:
# Using numpy
import numpy as np
import random
a = np.array([[random.randint(2,10) for _ in range(3)] for _ in range(3)])
print(a)

[[ 2 10 10]
 [ 4  8  8]
 [ 3 10  8]]


In [9]:
# To find determinant of matrices
m = [[1,0,2],[0,2,1],[4,0,3]]
det = 0
s = 0
for i in range(3):
    r = set(range(1,3)) # 1,2
    c = set(range(3))    
    c.remove(i)
    s = 1 if i%2==0 else -1
    sdet = (m[min(r)][min(c)]*m[max(r)][max(c)]) - (m[max(r)][min(c)]*m[min(r)][max(c)])
    det += s*sdet*m[0][i]

print(det)


-10


In [10]:
m[1:3]

[[0, 2, 1], [4, 0, 3]]